# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeohashExpressions
                                 A QGIS plugin
 This plugin adds four expression functions to work with geohash
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-12-09
        copyright            : (C) 2023 by Valentin BUIRA
        email                : valentin.buira at gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeohashExpressions class from file GeohashExpressions.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geohash_expressions import GeohashExpressions
    return GeohashExpressions(iface)
